services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8080:5435"
    networks:
      - backend-network
    depends_on:
      - db-container
    volumes:
      - ./migrations:/usr/local/migrations
  
  db-container:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB__SUPERUSER}
      POSTGRES_PASSWORD: ${DB__SUPERUSER_PASSWORD}
      POSTGRES_DB: ${DB__NAME}
      DB__USER: ${DB__USERNAME}
      DB__PASSWORD: ${DB__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - backend-network

volumes:
  db_data: {}

networks:
  backend-network: {}